const query = `select 
Id,
AccountId,
CPAContactName__c,
CPAEmailAddress__c,
CPAName__c,
CPAPhoneNumber__c,
Cell_Phone__c,
Company_Name_IF_Any__c,
Company_Phone__c,
Contact_Role__c,
Contact_Type__c,
Department,
Email,
Fax,
Gift__c,
HealthAgencyName__c,
HealthContactName__c,
HealthEmailAddress__c,
HealthPhoneNumber__c,
IndividualId,
Jigsaw,
LastCURequestDate,
LastCUUpdateDate,
MailingStreet, MailingCity, MailingState, MailingCountry, MailingPostalCode, MailingLatitude, MailingLongitude,
MobilePhone,
Salutation, FirstName, LastName,
Other_Company_Name__c,
Other_Contact_Name__c,
Other_Email_Address__c,
Other_Phone_Number__c,
OwnerId,
Ownership__c,
P_C_Agency_Name__c,
P_C_Contact_Name__c,
P_C_Email_Address__c,
P_C_Phone_Number__c,
Phone,
ReportsToId,
Status__c,
Title,
Type_of_Service_Partner__c,
AssistantName,
AssistantPhone,
Birthdate,
Description,
DoNotCall,
HasOptedOutOfEmail,
HasOptedOutOfFax,
HomePhone,
LeadSource,
OtherStreet, OtherCity, OtherState, OtherCountry, OtherPostalCode, OtherLatitude, OtherLongitude,
OtherPhone,
Web_Address__c 
from Contact`; 

exports.contactQuery = query;

// GenderIdentity,
// Pronouns,