const query = `select 
Id,
Street, City, State, Country, PostalCode,
AnnualRevenue,
Business_Structure__c,
Company,
Contact_Type__c,
Contract_Type__c,
Current_Generator_s__c,
Current_Payroll_Provider__c,
DBA_Name__c,
Description,
DoNotCall,
EIN__c,
Email,
Employee_Tier__c,
Fax,
Grade__c,
HasOptedOutOfEmail,
HasOptedOutOfFax,
Health_Exp_Date__c,
Hubspot_Scoring__c,
Hubspot_Source__c,
Identify_Other_or_Name_of_Source__c,
IndividualId,
Industry,
Industry_Code__c,
Jigsaw,
LastTransferDate,
LeadSource,
Legal_Name__c,
MobilePhone,
Multiple_States__c,
Salutation, FirstName, LastName,
NumberOfEmployees,
Other_Contact_Name__c,
Other_Email_Address__c,
Other_Industry__c,
Other_Lead_Source__c,
Other_Phone_Number__c,
OwnerId,
PEO_Payroll_Renewal__c,
PEPY__c,
Phone,
Primary__c,
Priority__c,
PropelHR_Employee_Referral__c,
Rating,
Referring_Broker__c,
Referring_Party__c,
SIC_Code__c,
Selling_Option__c,
States__c,
Status,
Title,
Type__c,
WC_Class_Code__c,
WC_Exp_Date__c,
Website 
from Lead`; 

exports.leadQuery = query;


// CampaignId,
// GenderIdentity,
// Pronouns,